/* ============================================================================
   seed-toys.js  —  Shakebox starter content
   ----------------------------------------------------------------------------
   THIS FILE IS SAFE TO EDIT. You do not need to be a programmer.

   There are two lists below.

   1) STARTER_TOYS  — the toys offered as one-tap "quick add" chips in the
      parent's Add-a-toy sheet. Each line looks like:

          { name: "Basketball", emoji: "🏀", category: "Active & outdoor" },

      • name     : what the kid sees. Keep it short and plain.
      • emoji    : one emoji. Copy/paste any emoji you like between the quotes.
      • category : MUST be one of the seven category names spelled EXACTLY as
                   they appear in CATEGORIES just below (capital letters and the
                   "&" matter). If you misspell it, the toy won't show up.

      To add a toy: copy a whole line, paste it, and change the words between
      the quotes. To remove one: delete its whole line. Commas at the end of
      each line matter — keep them.

   2) EMOJI_KEYWORDS — when a parent types a toy name that isn't in the starter
      pack, Shakebox guesses an emoji by looking for one of these keywords
      inside what they typed (first match wins). If nothing matches it uses 🎁.

          { word: "dragon", emoji: "🐉" },

      Lowercase words only. Order matters a little: more specific words should
      come before more general ones (e.g. "fire truck" before "truck").

   That's it. Save the file and reload Shakebox to see your changes.
   ========================================================================== */

// The seven categories. Do not rename these — the app groups chips by them.
const CATEGORIES = [
  "Build & create",
  "Games & puzzles",
  "Active & outdoor",
  "Figures & vehicles",
  "Arts & crafts",
  "Plush & pretend",
  "Tech & screens",
];

const STARTER_TOYS = [
  // ---- Build & create ----
  { name: "LEGO Creator set", emoji: "🧱", category: "Build & create" },
  { name: "Wooden blocks", emoji: "🪵", category: "Build & create" },
  { name: "Magnetic tiles", emoji: "🧲", category: "Build & create" },
  { name: "Model kit", emoji: "🔧", category: "Build & create" },
  { name: "K'nex set", emoji: "⚙️", category: "Build & create" },
  { name: "Marble run", emoji: "🌀", category: "Build & create" },
  { name: "Play-Doh set", emoji: "🎨", category: "Build & create" },
  { name: "Building bricks", emoji: "🧱", category: "Build & create" },
  { name: "Lincoln Logs", emoji: "🪵", category: "Build & create" },
  { name: "Snap circuits", emoji: "🔌", category: "Build & create" },
  { name: "Gear set", emoji: "⚙️", category: "Build & create" },
  { name: "Foam blocks", emoji: "🧱", category: "Build & create" },
  { name: "Sand kinetic set", emoji: "🏖️", category: "Build & create" },

  // ---- Games & puzzles ----
  { name: "1000-piece puzzle", emoji: "🧩", category: "Games & puzzles" },
  { name: "Uno deck", emoji: "🃏", category: "Games & puzzles" },
  { name: "Dominoes", emoji: "🎲", category: "Games & puzzles" },
  { name: "Chess set", emoji: "♟️", category: "Games & puzzles" },
  { name: "Rubik's cube", emoji: "🧊", category: "Games & puzzles" },
  { name: "Checkers", emoji: "🔴", category: "Games & puzzles" },
  { name: "Jenga tower", emoji: "🗼", category: "Games & puzzles" },
  { name: "Connect Four", emoji: "🔵", category: "Games & puzzles" },
  { name: "Playing cards", emoji: "🃏", category: "Games & puzzles" },
  { name: "Board game", emoji: "🎲", category: "Games & puzzles" },
  { name: "Memory match", emoji: "🧠", category: "Games & puzzles" },
  { name: "Battleship", emoji: "🚢", category: "Games & puzzles" },
  { name: "Word search book", emoji: "📖", category: "Games & puzzles" },

  // ---- Active & outdoor ----
  { name: "Basketball", emoji: "🏀", category: "Active & outdoor" },
  { name: "Soccer ball", emoji: "⚽", category: "Active & outdoor" },
  { name: "Skateboard", emoji: "🛹", category: "Active & outdoor" },
  { name: "Box kite", emoji: "🪁", category: "Active & outdoor" },
  { name: "Scooter", emoji: "🛴", category: "Active & outdoor" },
  { name: "Jump rope", emoji: "🤸", category: "Active & outdoor" },
  { name: "Frisbee", emoji: "🥏", category: "Active & outdoor" },
  { name: "Hula hoop", emoji: "⭕", category: "Active & outdoor" },
  { name: "Bicycle", emoji: "🚲", category: "Active & outdoor" },
  { name: "Roller skates", emoji: "🛼", category: "Active & outdoor" },
  { name: "Bubble wand", emoji: "🫧", category: "Active & outdoor" },
  { name: "Water balloons", emoji: "🎈", category: "Active & outdoor" },
  { name: "Sidewalk chalk", emoji: "🖍️", category: "Active & outdoor" },
  { name: "Pogo stick", emoji: "🦘", category: "Active & outdoor" },

  // ---- Figures & vehicles ----
  { name: "Dinosaur figures", emoji: "🦖", category: "Figures & vehicles" },
  { name: "Remote-control car", emoji: "🚗", category: "Figures & vehicles" },
  { name: "Wooden train set", emoji: "🚂", category: "Figures & vehicles" },
  { name: "Action figures", emoji: "🤖", category: "Figures & vehicles" },
  { name: "Toy helicopter", emoji: "🚁", category: "Figures & vehicles" },
  { name: "Race car", emoji: "🏎️", category: "Figures & vehicles" },
  { name: "Fire truck", emoji: "🚒", category: "Figures & vehicles" },
  { name: "Dump truck", emoji: "🚚", category: "Figures & vehicles" },
  { name: "Toy airplane", emoji: "✈️", category: "Figures & vehicles" },
  { name: "Toy boat", emoji: "⛵", category: "Figures & vehicles" },
  { name: "Dollhouse", emoji: "🏠", category: "Figures & vehicles" },
  { name: "Robot toy", emoji: "🤖", category: "Figures & vehicles" },
  { name: "Farm animals", emoji: "🐮", category: "Figures & vehicles" },
  { name: "Rocket ship", emoji: "🚀", category: "Figures & vehicles" },

  // ---- Arts & crafts ----
  { name: "Watercolor set", emoji: "🎨", category: "Arts & crafts" },
  { name: "Sketchbook", emoji: "✏️", category: "Arts & crafts" },
  { name: "Bracelet kit", emoji: "🧵", category: "Arts & crafts" },
  { name: "Crayon box", emoji: "🖍️", category: "Arts & crafts" },
  { name: "Colored pencils", emoji: "✏️", category: "Arts & crafts" },
  { name: "Sticker book", emoji: "✨", category: "Arts & crafts" },
  { name: "Origami paper", emoji: "🦢", category: "Arts & crafts" },
  { name: "Beads set", emoji: "📿", category: "Arts & crafts" },
  { name: "Modeling clay", emoji: "🟢", category: "Arts & crafts" },
  { name: "Paint by numbers", emoji: "🖼️", category: "Arts & crafts" },
  { name: "Scissors and glue", emoji: "✂️", category: "Arts & crafts" },
  { name: "Friendship pins", emoji: "🧷", category: "Arts & crafts" },
  { name: "Stamp set", emoji: "📮", category: "Arts & crafts" },

  // ---- Plush & pretend ----
  { name: "Teddy bear", emoji: "🧸", category: "Plush & pretend" },
  { name: "Baby doll", emoji: "🪆", category: "Plush & pretend" },
  { name: "Stuffed bunny", emoji: "🐰", category: "Plush & pretend" },
  { name: "Play kitchen", emoji: "🍳", category: "Plush & pretend" },
  { name: "Tea set", emoji: "🫖", category: "Plush & pretend" },
  { name: "Doctor kit", emoji: "🩺", category: "Plush & pretend" },
  { name: "Dress-up costume", emoji: "👑", category: "Plush & pretend" },
  { name: "Puppet", emoji: "🎭", category: "Plush & pretend" },
  { name: "Toy cash register", emoji: "💰", category: "Plush & pretend" },
  { name: "Tool bench", emoji: "🛠️", category: "Plush & pretend" },
  { name: "Plush dinosaur", emoji: "🦕", category: "Plush & pretend" },
  { name: "Stuffed puppy", emoji: "🐶", category: "Plush & pretend" },
  { name: "Toy food set", emoji: "🍎", category: "Plush & pretend" },

  // ---- Tech & screens ----
  { name: "Nintendo Switch", emoji: "🎮", category: "Tech & screens" },
  { name: "Tablet", emoji: "📱", category: "Tech & screens" },
  { name: "Kids camera", emoji: "📷", category: "Tech & screens" },
  { name: "Walkie-talkies", emoji: "📻", category: "Tech & screens" },
  { name: "Coding robot", emoji: "🤖", category: "Tech & screens" },
  { name: "Handheld game", emoji: "🕹️", category: "Tech & screens" },
  { name: "Karaoke mic", emoji: "🎤", category: "Tech & screens" },
  { name: "Headphones", emoji: "🎧", category: "Tech & screens" },
  { name: "Drone", emoji: "🚁", category: "Tech & screens" },
  { name: "Electronic keyboard", emoji: "🎹", category: "Tech & screens" },
  { name: "Kids smartwatch", emoji: "⌚", category: "Tech & screens" },
  { name: "VR headset", emoji: "🥽", category: "Tech & screens" },
];

const EMOJI_KEYWORDS = [
  // vehicles (specific before general)
  { word: "fire truck", emoji: "🚒" },
  { word: "garbage truck", emoji: "🚛" },
  { word: "dump truck", emoji: "🚚" },
  { word: "monster truck", emoji: "🛻" },
  { word: "truck", emoji: "🚚" },
  { word: "race car", emoji: "🏎️" },
  { word: "police car", emoji: "🚓" },
  { word: "car", emoji: "🚗" },
  { word: "train", emoji: "🚂" },
  { word: "airplane", emoji: "✈️" },
  { word: "plane", emoji: "✈️" },
  { word: "helicopter", emoji: "🚁" },
  { word: "rocket", emoji: "🚀" },
  { word: "boat", emoji: "⛵" },
  { word: "ship", emoji: "🚢" },
  { word: "tractor", emoji: "🚜" },
  { word: "bus", emoji: "🚌" },
  { word: "bike", emoji: "🚲" },
  { word: "bicycle", emoji: "🚲" },
  { word: "scooter", emoji: "🛴" },
  { word: "skateboard", emoji: "🛹" },
  { word: "skates", emoji: "🛼" },
  { word: "submarine", emoji: "🚤" },
  // build
  { word: "lego", emoji: "🧱" },
  { word: "block", emoji: "🧱" },
  { word: "brick", emoji: "🧱" },
  { word: "magnetic", emoji: "🧲" },
  { word: "magnet", emoji: "🧲" },
  { word: "marble", emoji: "🌀" },
  { word: "circuit", emoji: "🔌" },
  { word: "gear", emoji: "⚙️" },
  { word: "tool", emoji: "🛠️" },
  { word: "clay", emoji: "🟢" },
  { word: "play-doh", emoji: "🎨" },
  { word: "playdoh", emoji: "🎨" },
  { word: "dough", emoji: "🎨" },
  { word: "kinetic sand", emoji: "🏖️" },
  { word: "sand", emoji: "🏖️" },
  // games & puzzles
  { word: "puzzle", emoji: "🧩" },
  { word: "jigsaw", emoji: "🧩" },
  { word: "chess", emoji: "♟️" },
  { word: "checkers", emoji: "🔴" },
  { word: "domino", emoji: "🎲" },
  { word: "dice", emoji: "🎲" },
  { word: "cards", emoji: "🃏" },
  { word: "card", emoji: "🃏" },
  { word: "uno", emoji: "🃏" },
  { word: "jenga", emoji: "🗼" },
  { word: "board game", emoji: "🎲" },
  { word: "rubik", emoji: "🧊" },
  { word: "cube", emoji: "🧊" },
  { word: "bingo", emoji: "🎱" },
  { word: "maze", emoji: "🌀" },
  // active & outdoor / sports
  { word: "basketball", emoji: "🏀" },
  { word: "soccer", emoji: "⚽" },
  { word: "football", emoji: "🏈" },
  { word: "baseball", emoji: "⚾" },
  { word: "tennis", emoji: "🎾" },
  { word: "volleyball", emoji: "🏐" },
  { word: "golf", emoji: "⛳" },
  { word: "hockey", emoji: "🏒" },
  { word: "bowling", emoji: "🎳" },
  { word: "ping pong", emoji: "🏓" },
  { word: "badminton", emoji: "🏸" },
  { word: "ball", emoji: "⚽" },
  { word: "kite", emoji: "🪁" },
  { word: "jump rope", emoji: "🤸" },
  { word: "frisbee", emoji: "🥏" },
  { word: "hula", emoji: "⭕" },
  { word: "bubble", emoji: "🫧" },
  { word: "balloon", emoji: "🎈" },
  { word: "chalk", emoji: "🖍️" },
  { word: "pool", emoji: "🏊" },
  { word: "trampoline", emoji: "🤸" },
  { word: "pogo", emoji: "🦘" },
  { word: "sled", emoji: "🛷" },
  { word: "ski", emoji: "🎿" },
  { word: "tent", emoji: "⛺" },
  // figures & animals
  { word: "dinosaur", emoji: "🦖" },
  { word: "dino", emoji: "🦖" },
  { word: "dragon", emoji: "🐉" },
  { word: "robot", emoji: "🤖" },
  { word: "action figure", emoji: "🤖" },
  { word: "unicorn", emoji: "🦄" },
  { word: "horse", emoji: "🐴" },
  { word: "pony", emoji: "🐴" },
  { word: "dog", emoji: "🐶" },
  { word: "puppy", emoji: "🐶" },
  { word: "cat", emoji: "🐱" },
  { word: "kitten", emoji: "🐱" },
  { word: "bunny", emoji: "🐰" },
  { word: "rabbit", emoji: "🐰" },
  { word: "bear", emoji: "🧸" },
  { word: "teddy", emoji: "🧸" },
  { word: "lion", emoji: "🦁" },
  { word: "tiger", emoji: "🐯" },
  { word: "elephant", emoji: "🐘" },
  { word: "dolphin", emoji: "🐬" },
  { word: "shark", emoji: "🦈" },
  { word: "dragonfly", emoji: "🦋" },
  { word: "butterfly", emoji: "🦋" },
  { word: "penguin", emoji: "🐧" },
  { word: "frog", emoji: "🐸" },
  { word: "owl", emoji: "🦉" },
  { word: "farm", emoji: "🐮" },
  { word: "cow", emoji: "🐮" },
  { word: "dollhouse", emoji: "🏠" },
  { word: "doll", emoji: "🪆" },
  { word: "figure", emoji: "🧍" },
  { word: "soldier", emoji: "🪖" },
  { word: "knight", emoji: "🛡️" },
  { word: "castle", emoji: "🏰" },
  { word: "pirate", emoji: "🏴‍☠️" },
  { word: "princess", emoji: "👑" },
  { word: "superhero", emoji: "🦸" },
  { word: "ninja", emoji: "🥷" },
  // arts & crafts
  { word: "paint", emoji: "🎨" },
  { word: "watercolor", emoji: "🎨" },
  { word: "crayon", emoji: "🖍️" },
  { word: "marker", emoji: "🖊️" },
  { word: "pencil", emoji: "✏️" },
  { word: "sketch", emoji: "✏️" },
  { word: "draw", emoji: "✏️" },
  { word: "color", emoji: "🖍️" },
  { word: "sticker", emoji: "✨" },
  { word: "glitter", emoji: "✨" },
  { word: "bead", emoji: "📿" },
  { word: "bracelet", emoji: "🧵" },
  { word: "thread", emoji: "🧵" },
  { word: "yarn", emoji: "🧶" },
  { word: "knit", emoji: "🧶" },
  { word: "sew", emoji: "🪡" },
  { word: "origami", emoji: "🦢" },
  { word: "scissors", emoji: "✂️" },
  { word: "glue", emoji: "🧴" },
  { word: "stamp", emoji: "📮" },
  { word: "craft", emoji: "🎨" },
  // plush & pretend / household
  { word: "kitchen", emoji: "🍳" },
  { word: "tea set", emoji: "🫖" },
  { word: "doctor", emoji: "🩺" },
  { word: "nurse", emoji: "🩺" },
  { word: "vet", emoji: "🩺" },
  { word: "costume", emoji: "👑" },
  { word: "crown", emoji: "👑" },
  { word: "puppet", emoji: "🎭" },
  { word: "cash register", emoji: "💰" },
  { word: "money", emoji: "💰" },
  { word: "food", emoji: "🍎" },
  { word: "cook", emoji: "🍳" },
  { word: "wand", emoji: "🪄" },
  { word: "magic", emoji: "🪄" },
  { word: "fairy", emoji: "🧚" },
  // tech & screens / music
  { word: "nintendo", emoji: "🎮" },
  { word: "switch", emoji: "🎮" },
  { word: "playstation", emoji: "🎮" },
  { word: "xbox", emoji: "🎮" },
  { word: "video game", emoji: "🎮" },
  { word: "game", emoji: "🎮" },
  { word: "controller", emoji: "🎮" },
  { word: "tablet", emoji: "📱" },
  { word: "ipad", emoji: "📱" },
  { word: "phone", emoji: "📱" },
  { word: "camera", emoji: "📷" },
  { word: "walkie", emoji: "📻" },
  { word: "radio", emoji: "📻" },
  { word: "drone", emoji: "🚁" },
  { word: "watch", emoji: "⌚" },
  { word: "headphone", emoji: "🎧" },
  { word: "vr", emoji: "🥽" },
  { word: "keyboard", emoji: "🎹" },
  { word: "piano", emoji: "🎹" },
  { word: "guitar", emoji: "🎸" },
  { word: "drum", emoji: "🥁" },
  { word: "microphone", emoji: "🎤" },
  { word: "mic", emoji: "🎤" },
  { word: "karaoke", emoji: "🎤" },
  { word: "music", emoji: "🎵" },
  { word: "flute", emoji: "🎶" },
  { word: "trumpet", emoji: "🎺" },
  { word: "violin", emoji: "🎻" },
  // books & misc
  { word: "book", emoji: "📖" },
  { word: "story", emoji: "📖" },
  { word: "telescope", emoji: "🔭" },
  { word: "microscope", emoji: "🔬" },
  { word: "science", emoji: "🔬" },
  { word: "magnifying", emoji: "🔍" },
  { word: "rock", emoji: "🪨" },
  { word: "gem", emoji: "💎" },
  { word: "treasure", emoji: "💎" },
  { word: "flag", emoji: "🚩" },
  { word: "star", emoji: "⭐" },
  { word: "heart", emoji: "❤️" },
  { word: "flower", emoji: "🌸" },
  { word: "garden", emoji: "🌱" },
];

// Expose to the app (no modules in this zero-build project — just globals).
window.SHAKEBOX_SEED = { CATEGORIES, STARTER_TOYS, EMOJI_KEYWORDS };
